/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.ListaEquipos;
import controlador.SegundaFase;
import controlador.SimularFaseGrupos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import modelo.Equipo;
import modelo.FaseGrupos;
import modelo.Grupo;

/**
 *
 * @author Escar
 */
public class VentanaMundial extends javax.swing.JDialog {
    ListaEquipos equipos = new ListaEquipos();
    /**
     * Creates new form VentanaMundial
     */
    public VentanaMundial(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSimular = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mundial");

        botonSimular.setText("Simular");
        botonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimularActionPerformed(evt);
            }
        });

        resultado.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSimular)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(botonSimular)
                .addGap(30, 30, 30)
                .addComponent(resultado)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimularActionPerformed
        // TODO add your handling code here:
        ListaEquipos equipos = new ListaEquipos();
        try {
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMundial.class.getName()).log(Level.SEVERE, null, ex);
        }
        Grupo A= new Grupo("A", equipos.getEquipos(6),  equipos.getEquipos(13),  equipos.getEquipos(25),  equipos.getEquipos(7));
                Grupo B= new Grupo("B", equipos.getEquipos(15),  equipos.getEquipos(27), equipos.getEquipos(8),  equipos.getEquipos(3));
                Grupo C= new Grupo("C", equipos.getEquipos(9), equipos.getEquipos(19), equipos.getEquipos(11), equipos.getEquipos(24));
                Grupo D= new Grupo("D", equipos.getEquipos(31), equipos.getEquipos(12), equipos.getEquipos(21), equipos.getEquipos(23));
                Grupo E= new Grupo("E", equipos.getEquipos(30),  equipos.getEquipos(14),  equipos.getEquipos(17),  equipos.getEquipos(20));
                Grupo F= new Grupo("F", equipos.getEquipos(2), equipos.getEquipos(5), equipos.getEquipos(22), equipos.getEquipos(26));
                Grupo G= new Grupo("G", equipos.getEquipos(0), equipos.getEquipos(28), equipos.getEquipos(18), equipos.getEquipos(16));
                Grupo H= new Grupo("H", equipos.getEquipos(4), equipos.getEquipos(1), equipos.getEquipos(29), equipos.getEquipos(10));
       
                FaseGrupos fase = new FaseGrupos(A,B,C,D,E,F,G,H);
                Equipo[] winners=SimularFaseGrupos.simular(fase);
        
        
                for(int i=0;i<8;i++)
                    System.out.println("Ganadores grupo:"+fase.getGrupos(i).getLetra()+" "+fase.getGrupos(i).getGanadores()[0].getNombre().trim()+"="+fase.getGrupos(i).getGanadores()[0].getPuntos()+", "+fase.getGrupos(i).getGanadores()[1].getNombre().trim()+"= "+fase.getGrupos(i).getGanadores()[1].getPuntos());
        

        
                System.out.println("\n=================================\n");
 
                Equipo Ganadorsh =SegundaFase.simular(winners);
        
                resultado.setText("El Equipo ganador del Mundial es: " + Ganadorsh.getNombre().trim() );
    }//GEN-LAST:event_botonSimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    VentanaMundial dialog = new VentanaMundial(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaMundial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
