/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;
import controlador.*;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import modelo.Cancha;
import modelo.Pelota;
/**
 *
 * @author Escar
 * 
 * VentanaPartidos muestra por pantalla la simulacion de un partido y permite la interaccion de usuario
 */
public class VentanaPartidos extends javax.swing.JDialog {
    ListaEquipos equipos = new ListaEquipos();
    
    /**
     * Creates new form VentanaPartidos
     */
    public VentanaPartidos(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        equipos.ListaEquipos();
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        listaEquipo1.setModel(modelo);
        listaEquipo1.setEnabled(false);
        
        DefaultListModel modelo2 = new DefaultListModel();
        modelo2 = new DefaultListModel();
        for (int i = 0; i < 32; i++) {
            modelo2.addElement(equipos.getEquipos(i));
        }
        listaEquipo2.setModel(modelo2);
        listaEquipo2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEquipo2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEquipo1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonSimularPartido = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        botonSeleccionarEquipos = new javax.swing.JButton();
        botonEquiposAleatorios = new javax.swing.JButton();
        FormacionEquipo1 = new javax.swing.JComboBox();
        FormacionEquipo2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Partido");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Brazil 2014", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Partido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        listaEquipo2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEquipo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEquipo2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaEquipo2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 149, -1));

        listaEquipo1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEquipo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEquipo1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaEquipo1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 149, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Equipo 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Equipo 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        botonSimularPartido.setText("Simular");
        botonSimularPartido.setEnabled(false);
        botonSimularPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimularPartidoActionPerformed(evt);
            }
        });
        jPanel1.add(botonSimularPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 127, 47));

        resultado.setText("Resultado");
        resultado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                resultadoPropertyChange(evt);
            }
        });
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 531, 29));

        botonSeleccionarEquipos.setText("Seleccionar Equipos");
        botonSeleccionarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarEquiposActionPerformed(evt);
            }
        });
        jPanel1.add(botonSeleccionarEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        botonEquiposAleatorios.setText("Equipos Aleatorios");
        botonEquiposAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEquiposAleatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(botonEquiposAleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 127, -1));

        FormacionEquipo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Equilibrada (4-4-2)", "Volante Enganche (4-3-1-2)", "Ataque (4-3-3)", "Posesión (4-2-3-1)", "Laterales (3-5-2)", "Volantes (3-4-3)", "Defensa un delantero (5-4-1)", "Defensa dos delanteros (5-3-2)" }));
        FormacionEquipo1.setEnabled(false);
        FormacionEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormacionEquipo1ActionPerformed(evt);
            }
        });
        jPanel1.add(FormacionEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 149, -1));

        FormacionEquipo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Equilibrada (4-4-2)", "Volante Enganche (4-3-1-2)", "Ataque (4-3-3)", "Posesión (4-2-3-1)", "Laterales (3-5-2)", "Volantes (3-4-3)", "Defensa un delantero (5-4-1)", "Defensa dos delanteros (5-3-2)" }));
        FormacionEquipo2.setEnabled(false);
        FormacionEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormacionEquipo2ActionPerformed(evt);
            }
        });
        jPanel1.add(FormacionEquipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 149, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/imagen-03.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 211));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 638, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/roja.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 620, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSimularPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimularPartidoActionPerformed
        int index1 = listaEquipo1.getSelectedIndex();
        int index2 = listaEquipo2.getSelectedIndex();
        int form1 = FormacionEquipo1.getSelectedIndex()+1;
        int form2 = FormacionEquipo2.getSelectedIndex()+1;
        if(index1==index2){
            resultado.setText("Ingrese Equipos Distintos");
        }else{
        
        
        Pelota pelota=new Pelota();
        Cancha cancha=new Cancha();
        equipos.getEquipos(index1).setGoles(0);
        equipos.getEquipos(index2).setGoles(0);
        cancha.setEquipos(equipos.getEquipos(index1), 0);
        cancha.setEquipos(equipos.getEquipos(index2), 1);
        int[] n=SimularPartido.simularPartido(cancha, pelota, form1, form2);  // 0 0 arreglar formaciones
                       
        if(n[0]==0){
            resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
        }else if(n[0]==1){
            resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
        }else{
            int comp=0;//comprobante
            while(comp==0){
                int[] penal;
                penal=SimularPartido.penales(cancha);
                cancha.getEquipoX(0).setGoles(cancha.getEquipoX(0).getGoles()+penal[0]);
                cancha.getEquipoX(1).setGoles(cancha.getEquipoX(1).getGoles()+penal[1]);
                if (cancha.getEquipoX(0).getGoles()>cancha.getEquipoX(1).getGoles()){
                    n[0]=0;  
                    comp=1;
                }else if(cancha.getEquipoX(1).getGoles()>cancha.getEquipoX(0).getGoles()){
                    n[0]=1;
                    comp=1;
                }else{
                    comp=0;
                }
            }
            if(n[0]==0){
                resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
            }else if(n[0]==1){
                resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
            }
        }
 
        }
        listaEquipo1.setEnabled(false);
        listaEquipo2.setEnabled(false);
        botonSimularPartido.setEnabled(false);
    }//GEN-LAST:event_botonSimularPartidoActionPerformed

    private void resultadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_resultadoPropertyChange

        
    }//GEN-LAST:event_resultadoPropertyChange

    private void listaEquipo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEquipo1MouseClicked
        
    }//GEN-LAST:event_listaEquipo1MouseClicked

    private void listaEquipo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEquipo2MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_listaEquipo2MouseClicked

    private void botonSeleccionarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarEquiposActionPerformed
        // TODO add your handling code here:
        listaEquipo1.setEnabled(true);
        listaEquipo2.setEnabled(true);
        FormacionEquipo1.setEnabled(true);
        FormacionEquipo2.setEnabled(true);
        botonSimularPartido.setEnabled(true);
        
    }//GEN-LAST:event_botonSeleccionarEquiposActionPerformed

    private void botonEquiposAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEquiposAleatoriosActionPerformed
        // TODO add your handling code here:
        int index1=(int)(Math.random()*32);
        int index2 =(int)(Math.random()*32);
        while(index1==index2){
            index2 =(int)(Math.random()*32);
        }
        
        Pelota pelota=new Pelota();
        Cancha cancha=new Cancha();
        equipos.getEquipos(index1).setGoles(0);
        equipos.getEquipos(index2).setGoles(0);
        cancha.setEquipos(equipos.getEquipos(index1), 0);
        cancha.setEquipos(equipos.getEquipos(index2), 1);
        int[] n=SimularPartido.simularPartido(cancha, pelota, 0, 0);  // 0 0 arreglar formaciones
                       
        if(n[0]==0){
            resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
        }else if(n[0]==1){
            resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
        }else{
            int comp=0;//comprobante
            while(comp==0){
                int[] penal;
                penal=SimularPartido.penales(cancha);
                cancha.getEquipoX(0).setGoles(cancha.getEquipoX(0).getGoles()+penal[0]);
                cancha.getEquipoX(1).setGoles(cancha.getEquipoX(1).getGoles()+penal[1]);
                if (cancha.getEquipoX(0).getGoles()>cancha.getEquipoX(1).getGoles()){
                    n[0]=0;  
                    comp=1;
                }else if(cancha.getEquipoX(1).getGoles()>cancha.getEquipoX(0).getGoles()){
                    n[0]=1;
                    comp=1;
                }else{
                    comp=0;
                }
            }
            if(n[0]==0){
                resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
            }else if(n[0]==1){
                resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
            }
        }
 
        
    }//GEN-LAST:event_botonEquiposAleatoriosActionPerformed

    private void FormacionEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormacionEquipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormacionEquipo1ActionPerformed

    private void FormacionEquipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormacionEquipo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormacionEquipo2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FormacionEquipo1;
    private javax.swing.JComboBox FormacionEquipo2;
    private javax.swing.JButton botonEquiposAleatorios;
    private javax.swing.JButton botonSeleccionarEquipos;
    private javax.swing.JButton botonSimularPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaEquipo1;
    private javax.swing.JList listaEquipo2;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
