/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.ListaEquipos;
import controlador.SegundaFase;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import modelo.Equipo;

/**
 *
 * @author Escar
 */
public class VentanaSegunda extends javax.swing.JDialog {
    private VentanaP padre=(VentanaP) this.getParent();
    ListaEquipos equipos = new ListaEquipos();
    /**
     * Creates new form VentanaSegunda
     */
    public VentanaSegunda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        box1 = new javax.swing.JComboBox();
        box2 = new javax.swing.JComboBox();
        box3 = new javax.swing.JComboBox();
        box4 = new javax.swing.JComboBox();
        box5 = new javax.swing.JComboBox();
        box6 = new javax.swing.JComboBox();
        box7 = new javax.swing.JComboBox();
        box8 = new javax.swing.JComboBox();
        box9 = new javax.swing.JComboBox();
        box10 = new javax.swing.JComboBox();
        box11 = new javax.swing.JComboBox();
        box12 = new javax.swing.JComboBox();
        box13 = new javax.swing.JComboBox();
        box14 = new javax.swing.JComboBox();
        box15 = new javax.swing.JComboBox();
        box16 = new javax.swing.JComboBox();
        botonElegir = new javax.swing.JButton();
        botonAleatorio = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botonSimular = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Segunda Fase");

        jLabel2.setText("Equipo 1");

        jLabel3.setText("Equipo 2");

        jLabel4.setText("Equipo 3");

        jLabel5.setText("Equipo 4");

        jLabel6.setText("Equipo 5");

        jLabel7.setText("Equipo 6");

        jLabel8.setText("Equipo 7");

        jLabel9.setText("Equipo 8");

        jLabel10.setText("Equipo 9");

        jLabel11.setText("Equipo 10");

        jLabel12.setText("Equipo 11");

        jLabel13.setText("Equipo 12");

        jLabel14.setText("Equipo 13");

        jLabel15.setText("Equipo 14");

        jLabel16.setText("Equipo 15");

        jLabel17.setText("Equipo 16");

        box1.setEnabled(false);
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box2.setEnabled(false);
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box3.setEnabled(false);
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        box4.setEnabled(false);
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        box5.setEnabled(false);
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box6.setEnabled(false);
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });

        box7.setEnabled(false);
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });

        box8.setEnabled(false);
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });

        box9.setEnabled(false);
        box9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box9ActionPerformed(evt);
            }
        });

        box10.setEnabled(false);
        box10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box10ActionPerformed(evt);
            }
        });

        box11.setEnabled(false);
        box11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box11ActionPerformed(evt);
            }
        });

        box12.setEnabled(false);
        box12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box12ActionPerformed(evt);
            }
        });

        box13.setEnabled(false);
        box13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box13ActionPerformed(evt);
            }
        });

        box14.setEnabled(false);
        box14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box14ActionPerformed(evt);
            }
        });

        box15.setEnabled(false);
        box15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box15ActionPerformed(evt);
            }
        });

        box16.setEnabled(false);
        box16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box16ActionPerformed(evt);
            }
        });

        botonElegir.setText("Elegir Equipos");
        botonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElegirActionPerformed(evt);
            }
        });

        botonAleatorio.setText("Equipos Aleatorios");
        botonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAleatorioActionPerformed(evt);
            }
        });

        jButton3.setText("Por fase de Grupos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botonSimular.setText("Simular");
        botonSimular.setEnabled(false);
        botonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimularActionPerformed(evt);
            }
        });

        resultado.setText("resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(botonElegir)
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel14))
                                            .addGap(100, 100, 100)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel15)
                                                .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(box14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(100, 100, 100))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(85, 85, 85))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(150, 150, 150)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonSimular)
                                        .addComponent(botonAleatorio))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(box13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(247, 247, 247)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12))
                                        .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel17)
                                        .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(box12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(box16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(box15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButton3)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonElegir)
                    .addComponent(botonAleatorio)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonSimular)
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElegirActionPerformed
        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaSegunda.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        box1.setModel(modelo);
        box1.setEnabled(true);
    }//GEN-LAST:event_botonElegirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
        int index=box1.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index);
        box2.setModel(modelo);
        box2.setEnabled(true);
        box1.setEnabled(false);
                                 
    }//GEN-LAST:event_box1ActionPerformed

    private void box9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box9ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        box10.setModel(modelo);
        box10.setEnabled(true);
        box9.setEnabled(false);
    }//GEN-LAST:event_box9ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        box3.setModel(modelo);
        box3.setEnabled(true);
        box2.setEnabled(false);
    }//GEN-LAST:event_box2ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        box4.setModel(modelo);
        box4.setEnabled(true);
        box3.setEnabled(false);
    }//GEN-LAST:event_box3ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        box5.setModel(modelo);
        box5.setEnabled(true);
        box4.setEnabled(false);
    }//GEN-LAST:event_box4ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        box6.setModel(modelo);
        box6.setEnabled(true);
        box5.setEnabled(false);
    }//GEN-LAST:event_box5ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        box7.setModel(modelo);
        box7.setEnabled(true);
        box6.setEnabled(false);
    }//GEN-LAST:event_box6ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        box8.setModel(modelo);
        box8.setEnabled(true);
        box7.setEnabled(false);
    }//GEN-LAST:event_box7ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        box9.setModel(modelo);
        box9.setEnabled(true);
        box8.setEnabled(false);
    }//GEN-LAST:event_box8ActionPerformed

    private void box10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box10ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        box11.setModel(modelo);
        box11.setEnabled(true);
        box10.setEnabled(false);
    }//GEN-LAST:event_box10ActionPerformed

    private void box11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box11ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        box12.setModel(modelo);
        box12.setEnabled(true);
        box11.setEnabled(false);
    }//GEN-LAST:event_box11ActionPerformed

    private void box12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box12ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        box13.setModel(modelo);
        box13.setEnabled(true);
        box12.setEnabled(false);
    }//GEN-LAST:event_box12ActionPerformed

    private void box13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box13ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();
        int index13=box13.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        modelo.removeElementAt(index13);
        box14.setModel(modelo);
        box14.setEnabled(true);
        box13.setEnabled(false);
    }//GEN-LAST:event_box13ActionPerformed

    private void box14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box14ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();
        int index13=box13.getSelectedIndex();
        int index14=box14.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        modelo.removeElementAt(index13);
        modelo.removeElementAt(index14);
        box15.setModel(modelo);
        box15.setEnabled(true);
        box14.setEnabled(false);
    }//GEN-LAST:event_box14ActionPerformed

    private void box15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box15ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();
        int index13=box13.getSelectedIndex();
        int index14=box14.getSelectedIndex();
        int index15=box15.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        modelo.removeElementAt(index13);
        modelo.removeElementAt(index14);
        modelo.removeElementAt(index15);
        box16.setModel(modelo);
        box16.setEnabled(true);
        box15.setEnabled(false);
    }//GEN-LAST:event_box15ActionPerformed

    private void botonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimularActionPerformed
        // TODO add your handling code here:
        int[] grupo1=new int[16];
        for(int j=0;j<32;j++){
            Equipo a1=  (Equipo)box1.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a1.getId()){
                grupo1[0]=j;

            }
            Equipo b1=  (Equipo)box2.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b1.getId()){
                grupo1[1]=j;

            }
            Equipo c1=  (Equipo)box3.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c1.getId()){
                grupo1[2]=j;

            }
            Equipo d1=  (Equipo)box4.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d1.getId()){
                grupo1[3]=j;
            }
            Equipo a2=  (Equipo)box5.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a2.getId()){
                grupo1[4]=j;
            }
            Equipo b2=  (Equipo)box6.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b2.getId()){
                grupo1[5]=j;
            }
            Equipo c2=  (Equipo)box7.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c2.getId()){
                grupo1[6]=j;
            }
            Equipo d2=  (Equipo)box8.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d2.getId()){
                grupo1[7]=j;
            }
            Equipo a3=  (Equipo)box9.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a3.getId()){
                grupo1[8]=j;
            }
            Equipo b3=  (Equipo)box10.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b3.getId()){
                grupo1[9]=j;
            }
            Equipo c3=  (Equipo)box11.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c3.getId()){
                grupo1[10]=j;
            }
            Equipo d3=  (Equipo)box12.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d3.getId()){
                grupo1[11]=j;
            }
            Equipo a4=  (Equipo)box13.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a4.getId()){
                grupo1[12]=j;
            }
            Equipo b4=  (Equipo)box14.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b4.getId()){
                grupo1[13]=j;
            }
            Equipo c4=  (Equipo)box15.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c4.getId()){
                grupo1[14]=j;
            }
            Equipo d4=  (Equipo)box16.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d4.getId()){
                grupo1[15]=j;
            }
        }
        Equipo[] clasificados=new Equipo [16];
            for(int i=0;i<16;i++){
                    clasificados[i]=equipos.getEquipos(grupo1[i]);
            }
        
        Equipo ganador;
        ganador=SegundaFase.simular(clasificados);
        resultado.setText("\nEl ganador de la segunda Fase es "+ganador.getNombre().trim());
                        
        
    }//GEN-LAST:event_botonSimularActionPerformed

    private void box16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box16ActionPerformed
        // TODO add your handling code here:
        box16.setEnabled(false);
        botonSimular.setEnabled(true);
    }//GEN-LAST:event_box16ActionPerformed

    private void botonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAleatorioActionPerformed
        // TODO add your handling code here:
        int[] opcion2=new int[16];
                        
                        opcion2[0]=(int)(Math.random()*32);
                        do{
                            opcion2[1]=(int)(Math.random()*32);
                            if(opcion2[0]==opcion2[1]){
                                opcion2[1]=80; //salta condicion
                            }
                        }while(opcion2[1]>32);
                        
                        do{
                            
                            opcion2[2]=(int)(Math.random()*32);
                            if(opcion2[2]==opcion2[1] || opcion2[2]==opcion2[0]){
                                opcion2[2]=80; //salta condicion
                            }
                        }while(opcion2[2]>32);
                        
                        do{
                            opcion2[3]=(int)(Math.random()*32);
                            if(opcion2[3]==opcion2[0] || opcion2[2]==opcion2[1]|| opcion2[3]==opcion2[2]){
                                opcion2[3]=80; //salta condicion
                            }
                        }while(opcion2[3]>32);
                        
                        do{
                            opcion2[4]=(int)(Math.random()*32);
                            if(opcion2[4]==opcion2[0] || opcion2[4]==opcion2[1]|| opcion2[4]==opcion2[2]|| opcion2[4]==opcion2[3]){
                                opcion2[4]=80; //salta condicion
                            }
                        }while(opcion2[4]>32);
                        
                        do{
                            opcion2[5]=(int)(Math.random()*32);
                            if(opcion2[5]==opcion2[0] || opcion2[5]==opcion2[1]|| opcion2[5]==opcion2[2]|| opcion2[5]==opcion2[3]|| opcion2[5]==opcion2[4]){
                                opcion2[5]=80; //salta condicion
                            }
                        }while(opcion2[5]>32);
                        
                        do{
                            opcion2[6]=(int)(Math.random()*32);
                            if(opcion2[6]==opcion2[0] || opcion2[6]==opcion2[1]|| opcion2[6]==opcion2[2]|| opcion2[6]==opcion2[3]|| opcion2[6]==opcion2[4]|| opcion2[6]==opcion2[5]){
                                opcion2[6]=80; //salta condicion
                            }
                        }while(opcion2[6]>32);
                        
                        do{
                            opcion2[7]=(int)(Math.random()*32);
                            if(opcion2[7]==opcion2[0] || opcion2[7]==opcion2[1]|| opcion2[7]==opcion2[2]|| opcion2[7]==opcion2[3]|| opcion2[7]==opcion2[4]|| opcion2[7]==opcion2[5]|| opcion2[7]==opcion2[6]){
                                opcion2[7]=80; //salta condicion
                            }
                        }while(opcion2[7]>32);
                        
                        do{
                            opcion2[8]=(int)(Math.random()*32);
                            if(opcion2[8]==opcion2[0] || opcion2[8]==opcion2[1]|| opcion2[8]==opcion2[2]|| opcion2[8]==opcion2[3]|| opcion2[8]==opcion2[4]|| opcion2[8]==opcion2[5]|| opcion2[8]==opcion2[6]|| opcion2[8]==opcion2[7]){
                                opcion2[8]=80; //salta condicion
                            }
                        }while(opcion2[8]>32);
                        
                        do{
                            opcion2[9]=(int)(Math.random()*32);
                            if(opcion2[9]==opcion2[0] || opcion2[9]==opcion2[1]|| opcion2[9]==opcion2[2]|| opcion2[9]==opcion2[3]|| opcion2[9]==opcion2[4]|| opcion2[9]==opcion2[5]|| opcion2[9]==opcion2[6]|| opcion2[9]==opcion2[7]|| opcion2[9]==opcion2[8]){
                                opcion2[9]=80; //salta condicion
                            }
                        }while(opcion2[9]>32);
                        
                        do{
                            opcion2[10]=(int)(Math.random()*32);
                            if(opcion2[10]==opcion2[0] || opcion2[10]==opcion2[1]|| opcion2[10]==opcion2[2]|| opcion2[10]==opcion2[3]|| opcion2[10]==opcion2[4]|| opcion2[10]==opcion2[5]|| opcion2[10]==opcion2[6]|| opcion2[10]==opcion2[7]|| opcion2[10]==opcion2[8]|| opcion2[10]==opcion2[9]){
                                opcion2[10]=80; //salta condicion
                            }
                        }while(opcion2[10]>32);
                        
                        do{
                            opcion2[11]=(int)(Math.random()*32);
                            if(opcion2[11]==opcion2[0] || opcion2[11]==opcion2[1]|| opcion2[11]==opcion2[2]|| opcion2[11]==opcion2[3]|| opcion2[11]==opcion2[4]|| opcion2[11]==opcion2[5]|| opcion2[11]==opcion2[6]|| opcion2[11]==opcion2[7]|| opcion2[11]==opcion2[8]|| opcion2[11]==opcion2[9]|| opcion2[11]==opcion2[10]){
                                opcion2[11]=80; //salta condicion
                            }
                        }while(opcion2[11]>32);
                        
                        do{
                            opcion2[12]=(int)(Math.random()*32);
                            if(opcion2[12]==opcion2[0] || opcion2[12]==opcion2[1]|| opcion2[12]==opcion2[2]|| opcion2[12]==opcion2[3]|| opcion2[12]==opcion2[4]|| opcion2[12]==opcion2[5]|| opcion2[12]==opcion2[6]|| opcion2[12]==opcion2[7]|| opcion2[12]==opcion2[8]|| opcion2[12]==opcion2[9]|| opcion2[12]==opcion2[10]|| opcion2[12]==opcion2[11]){
                                opcion2[13]=80; //salta condicion
                            }
                        }while(opcion2[12]>32);
                        
                        do{
                            opcion2[13]=(int)(Math.random()*32);
                            if(opcion2[13]==opcion2[0] || opcion2[13]==opcion2[1]|| opcion2[13]==opcion2[2]|| opcion2[13]==opcion2[3]|| opcion2[13]==opcion2[4]|| opcion2[13]==opcion2[5]|| opcion2[13]==opcion2[6]|| opcion2[13]==opcion2[7]|| opcion2[13]==opcion2[8]|| opcion2[13]==opcion2[9]|| opcion2[13]==opcion2[10]|| opcion2[13]==opcion2[11]|| opcion2[13]==opcion2[12]){
                                opcion2[13]=80; //salta condicion
                            }
                        }while(opcion2[13]>32);
                        
                        do{
                            opcion2[14]=(int)(Math.random()*32);
                            if(opcion2[14]==opcion2[0] || opcion2[14]==opcion2[1]|| opcion2[14]==opcion2[2]|| opcion2[14]==opcion2[3]|| opcion2[14]==opcion2[4]|| opcion2[14]==opcion2[5]|| opcion2[14]==opcion2[6]|| opcion2[14]==opcion2[7]|| opcion2[14]==opcion2[8]|| opcion2[14]==opcion2[9]|| opcion2[14]==opcion2[10]|| opcion2[14]==opcion2[11]|| opcion2[14]==opcion2[12]|| opcion2[14]==opcion2[13]){
                                opcion2[14]=80; //salta condicion
                            }
                        }while(opcion2[14]>32);
                        
                        do{
                            opcion2[15]=(int)(Math.random()*32);
                            if(opcion2[15]==opcion2[0] || opcion2[15]==opcion2[1]|| opcion2[15]==opcion2[2]|| opcion2[15]==opcion2[3]|| opcion2[15]==opcion2[4]|| opcion2[15]==opcion2[5]|| opcion2[15]==opcion2[6]|| opcion2[15]==opcion2[7]|| opcion2[15]==opcion2[8]|| opcion2[15]==opcion2[9]|| opcion2[15]==opcion2[10]|| opcion2[15]==opcion2[11]|| opcion2[15]==opcion2[12]|| opcion2[15]==opcion2[13]|| opcion2[15]==opcion2[14]){
                                opcion2[15]=80; //salta condicion
                            }
                        }while(opcion2[15]>32);
                        
                       
                        
                        
                        Equipo[] clasificados=new Equipo [16];
                        for(int i=0;i<16;i++){
                            clasificados[i]=equipos.getEquipos(opcion2[i]);
                        }
                        Equipo ganador;
                        ganador=SegundaFase.simular(clasificados);
                        resultado.setText("\nEl ganador de la segunda Fase es "+ganador.getNombre().trim());
                        
    }//GEN-LAST:event_botonAleatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaSegunda dialog = new VentanaSegunda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAleatorio;
    private javax.swing.JButton botonElegir;
    private javax.swing.JButton botonSimular;
    private javax.swing.JComboBox box1;
    private javax.swing.JComboBox box10;
    private javax.swing.JComboBox box11;
    private javax.swing.JComboBox box12;
    private javax.swing.JComboBox box13;
    private javax.swing.JComboBox box14;
    private javax.swing.JComboBox box15;
    private javax.swing.JComboBox box16;
    private javax.swing.JComboBox box2;
    private javax.swing.JComboBox box3;
    private javax.swing.JComboBox box4;
    private javax.swing.JComboBox box5;
    private javax.swing.JComboBox box6;
    private javax.swing.JComboBox box7;
    private javax.swing.JComboBox box8;
    private javax.swing.JComboBox box9;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
