/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Escribir;
import controlador.ListaEquipos;
import controlador.SegundaFase;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import modelo.Equipo;

/**
 *
 * @author Escar
 * 
 * VentanaSegunda se encarga de mostrar por pantalla el desarrollo de la segunda
 * fase del mundial y permite la interaccion con usuario
 * 
 */
public class VentanaSegunda extends javax.swing.JDialog {
    private VentanaP padre=(VentanaP) this.getParent();
    ListaEquipos equipos = new ListaEquipos();
    /**
     * Creates new form VentanaSegunda
     */
    public VentanaSegunda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        box1 = new javax.swing.JComboBox();
        box2 = new javax.swing.JComboBox();
        box3 = new javax.swing.JComboBox();
        box4 = new javax.swing.JComboBox();
        box5 = new javax.swing.JComboBox();
        box6 = new javax.swing.JComboBox();
        box7 = new javax.swing.JComboBox();
        box8 = new javax.swing.JComboBox();
        box9 = new javax.swing.JComboBox();
        box10 = new javax.swing.JComboBox();
        box11 = new javax.swing.JComboBox();
        box12 = new javax.swing.JComboBox();
        box13 = new javax.swing.JComboBox();
        box14 = new javax.swing.JComboBox();
        box15 = new javax.swing.JComboBox();
        box16 = new javax.swing.JComboBox();
        botonElegir = new javax.swing.JButton();
        botonAleatorio = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botonSimular = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Segunda Fase");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Equipo 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 109, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Equipo 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 109, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Equipo 3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 109, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Equipo 4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 109, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Equipo 5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 167, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Equipo 6");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 167, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Equipo 7");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 167, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Equipo 8");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 167, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Equipo 9");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 222, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Equipo 10");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 222, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Equipo 11");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 222, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Equipo 12");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 222, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Equipo 13");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 276, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("Equipo 14");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 276, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Equipo 15");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 276, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setText("Equipo 16");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 276, -1, -1));

        box1.setEnabled(false);
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });
        jPanel1.add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 129, 130, -1));

        box2.setEnabled(false);
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });
        jPanel1.add(box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 129, 130, -1));

        box3.setEnabled(false);
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });
        jPanel1.add(box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 129, 130, -1));

        box4.setEnabled(false);
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });
        jPanel1.add(box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 129, 130, -1));

        box5.setEnabled(false);
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });
        jPanel1.add(box5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 188, 130, -1));

        box6.setEnabled(false);
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });
        jPanel1.add(box6, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 188, 130, -1));

        box7.setEnabled(false);
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });
        jPanel1.add(box7, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 188, 130, -1));

        box8.setEnabled(false);
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });
        jPanel1.add(box8, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 188, 130, -1));

        box9.setEnabled(false);
        box9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box9ActionPerformed(evt);
            }
        });
        jPanel1.add(box9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 242, 130, -1));

        box10.setEnabled(false);
        box10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box10ActionPerformed(evt);
            }
        });
        jPanel1.add(box10, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 242, 130, -1));

        box11.setEnabled(false);
        box11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box11ActionPerformed(evt);
            }
        });
        jPanel1.add(box11, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 242, 130, -1));

        box12.setEnabled(false);
        box12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box12ActionPerformed(evt);
            }
        });
        jPanel1.add(box12, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 242, 130, -1));

        box13.setEnabled(false);
        box13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box13ActionPerformed(evt);
            }
        });
        jPanel1.add(box13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 296, 130, -1));

        box14.setEnabled(false);
        box14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box14ActionPerformed(evt);
            }
        });
        jPanel1.add(box14, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 296, 130, -1));

        box15.setEnabled(false);
        box15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box15ActionPerformed(evt);
            }
        });
        jPanel1.add(box15, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 296, 130, -1));

        box16.setEnabled(false);
        box16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box16ActionPerformed(evt);
            }
        });
        jPanel1.add(box16, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 296, 130, -1));

        botonElegir.setText("Elegir Equipos");
        botonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElegirActionPerformed(evt);
            }
        });
        jPanel1.add(botonElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 68, 130, -1));

        botonAleatorio.setText("Equipos Aleatorios");
        botonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAleatorioActionPerformed(evt);
            }
        });
        jPanel1.add(botonAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 68, -1, -1));

        jButton3.setText("Por fase de Grupos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 68, 148, -1));

        botonSimular.setText("Simular");
        botonSimular.setEnabled(false);
        botonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimularActionPerformed(evt);
            }
        });
        jPanel1.add(botonSimular, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 187, 154, -1));

        resultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultado.setText("Resultado");
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 551, 291));

        jLabel1.setFont(new java.awt.Font("Brazil 2014", 0, 24)); // NOI18N
        jLabel1.setText("Segunda Fase");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/logo-copa.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, -1, -1));

        botonRegistro.setText("Registro");
        botonRegistro.setEnabled(false);
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 100, 50));

        jLabel20.setBackground(new java.awt.Color(153, 255, 153));
        jLabel20.setText("Espere unos segundos despues de simular");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, -1, -1));

        Fondo2.setForeground(new java.awt.Color(51, 204, 0));
        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/estadio.jpg"))); // NOI18N
        jPanel1.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElegirActionPerformed
        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaSegunda.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        box1.setModel(modelo);
        box1.setEnabled(true);
    }//GEN-LAST:event_botonElegirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VentanaH window= new VentanaH(padre, true);
        window.setVisible(true);
        resultado.setText("ACCION NO DISPONIBLE EN LA BETA :D ");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
        int index=box1.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index);
        box2.setModel(modelo);
        box2.setEnabled(true);
        box1.setEnabled(false);
                                 
    }//GEN-LAST:event_box1ActionPerformed

    private void box9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box9ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        box10.setModel(modelo);
        box10.setEnabled(true);
        box9.setEnabled(false);
    }//GEN-LAST:event_box9ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        box3.setModel(modelo);
        box3.setEnabled(true);
        box2.setEnabled(false);
    }//GEN-LAST:event_box2ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        box4.setModel(modelo);
        box4.setEnabled(true);
        box3.setEnabled(false);
    }//GEN-LAST:event_box3ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        box5.setModel(modelo);
        box5.setEnabled(true);
        box4.setEnabled(false);
    }//GEN-LAST:event_box4ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        box6.setModel(modelo);
        box6.setEnabled(true);
        box5.setEnabled(false);
    }//GEN-LAST:event_box5ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        box7.setModel(modelo);
        box7.setEnabled(true);
        box6.setEnabled(false);
    }//GEN-LAST:event_box6ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        box8.setModel(modelo);
        box8.setEnabled(true);
        box7.setEnabled(false);
    }//GEN-LAST:event_box7ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        box9.setModel(modelo);
        box9.setEnabled(true);
        box8.setEnabled(false);
    }//GEN-LAST:event_box8ActionPerformed

    private void box10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box10ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        box11.setModel(modelo);
        box11.setEnabled(true);
        box10.setEnabled(false);
    }//GEN-LAST:event_box10ActionPerformed

    private void box11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box11ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        box12.setModel(modelo);
        box12.setEnabled(true);
        box11.setEnabled(false);
    }//GEN-LAST:event_box11ActionPerformed

    private void box12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box12ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        box13.setModel(modelo);
        box13.setEnabled(true);
        box12.setEnabled(false);
    }//GEN-LAST:event_box12ActionPerformed

    private void box13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box13ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();
        int index13=box13.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        modelo.removeElementAt(index13);
        box14.setModel(modelo);
        box14.setEnabled(true);
        box13.setEnabled(false);
    }//GEN-LAST:event_box13ActionPerformed

    private void box14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box14ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();
        int index13=box13.getSelectedIndex();
        int index14=box14.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        modelo.removeElementAt(index13);
        modelo.removeElementAt(index14);
        box15.setModel(modelo);
        box15.setEnabled(true);
        box14.setEnabled(false);
    }//GEN-LAST:event_box14ActionPerformed

    private void box15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box15ActionPerformed
        // TODO add your handling code here:
        int index1=box1.getSelectedIndex();
        int index2=box2.getSelectedIndex();
        int index3=box3.getSelectedIndex();
        int index4=box4.getSelectedIndex();
        int index5=box5.getSelectedIndex();
        int index6=box6.getSelectedIndex();
        int index7=box7.getSelectedIndex();
        int index8=box8.getSelectedIndex();
        int index9=box9.getSelectedIndex();
        int index10=box10.getSelectedIndex();
        int index11=box11.getSelectedIndex();
        int index12=box12.getSelectedIndex();
        int index13=box13.getSelectedIndex();
        int index14=box14.getSelectedIndex();
        int index15=box15.getSelectedIndex();

        try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        modelo.removeElementAt(index1);
        modelo.removeElementAt(index2);
        modelo.removeElementAt(index3);
        modelo.removeElementAt(index4);
        modelo.removeElementAt(index5);
        modelo.removeElementAt(index6);
        modelo.removeElementAt(index7);
        modelo.removeElementAt(index8);
        modelo.removeElementAt(index9);
        modelo.removeElementAt(index10);
        modelo.removeElementAt(index11);
        modelo.removeElementAt(index12);
        modelo.removeElementAt(index13);
        modelo.removeElementAt(index14);
        modelo.removeElementAt(index15);
        box16.setModel(modelo);
        box16.setEnabled(true);
        box15.setEnabled(false);
    }//GEN-LAST:event_box15ActionPerformed

    private void botonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimularActionPerformed
        // TODO add your handling code here:
        int[] grupo1=new int[16];
        for(int j=0;j<32;j++){
            Equipo a1=  (Equipo)box1.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a1.getId()){
                grupo1[0]=j;

            }
            Equipo b1=  (Equipo)box2.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b1.getId()){
                grupo1[1]=j;

            }
            Equipo c1=  (Equipo)box3.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c1.getId()){
                grupo1[2]=j;

            }
            Equipo d1=  (Equipo)box4.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d1.getId()){
                grupo1[3]=j;
            }
            Equipo a2=  (Equipo)box5.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a2.getId()){
                grupo1[4]=j;
            }
            Equipo b2=  (Equipo)box6.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b2.getId()){
                grupo1[5]=j;
            }
            Equipo c2=  (Equipo)box7.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c2.getId()){
                grupo1[6]=j;
            }
            Equipo d2=  (Equipo)box8.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d2.getId()){
                grupo1[7]=j;
            }
            Equipo a3=  (Equipo)box9.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a3.getId()){
                grupo1[8]=j;
            }
            Equipo b3=  (Equipo)box10.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b3.getId()){
                grupo1[9]=j;
            }
            Equipo c3=  (Equipo)box11.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c3.getId()){
                grupo1[10]=j;
            }
            Equipo d3=  (Equipo)box12.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d3.getId()){
                grupo1[11]=j;
            }
            Equipo a4=  (Equipo)box13.getSelectedItem();
            if(equipos.getEquipos(j).getId()==a4.getId()){
                grupo1[12]=j;
            }
            Equipo b4=  (Equipo)box14.getSelectedItem();
            if(equipos.getEquipos(j).getId()==b4.getId()){
                grupo1[13]=j;
            }
            Equipo c4=  (Equipo)box15.getSelectedItem();
            if(equipos.getEquipos(j).getId()==c4.getId()){
                grupo1[14]=j;
            }
            Equipo d4=  (Equipo)box16.getSelectedItem();
            if(equipos.getEquipos(j).getId()==d4.getId()){
                grupo1[15]=j;
            }
        }
        Equipo[] clasificados=new Equipo [16];
            for(int i=0;i<16;i++){
                    clasificados[i]=equipos.getEquipos(grupo1[i]);
            }
        
        String s="";
        Escribir.Escribir(s, false);
        Equipo ganador;
        ganador=SegundaFase.simular(clasificados);
        resultado.setText("\nEl ganador de la segunda Fase es "+ganador.getNombre().trim());
        botonRegistro.setEnabled(true);
        
    }//GEN-LAST:event_botonSimularActionPerformed

    private void box16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box16ActionPerformed
        // TODO add your handling code here:
        box16.setEnabled(false);
        botonSimular.setEnabled(true);
    }//GEN-LAST:event_box16ActionPerformed

    private void botonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAleatorioActionPerformed
      try {
            // TODO add your handling code here:
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaSegunda.class.getName()).log(Level.SEVERE, null, ex);
        }
        int[] opcion2=new int[16];
                        
                        opcion2[0]=(int)(Math.random()*32);
                        do{
                            opcion2[1]=(int)(Math.random()*32);
                            if(opcion2[0]==opcion2[1]){
                                opcion2[1]=80; //salta condicion
                            }
                        }while(opcion2[1]>32);
                        
                        do{
                            
                            opcion2[2]=(int)(Math.random()*32);
                            if(opcion2[2]==opcion2[1] || opcion2[2]==opcion2[0]){
                                opcion2[2]=80; //salta condicion
                            }
                        }while(opcion2[2]>32);
                        
                        do{
                            opcion2[3]=(int)(Math.random()*32);
                            if(opcion2[3]==opcion2[0] || opcion2[2]==opcion2[1]|| opcion2[3]==opcion2[2]){
                                opcion2[3]=80; //salta condicion
                            }
                        }while(opcion2[3]>32);
                        
                        do{
                            opcion2[4]=(int)(Math.random()*32);
                            if(opcion2[4]==opcion2[0] || opcion2[4]==opcion2[1]|| opcion2[4]==opcion2[2]|| opcion2[4]==opcion2[3]){
                                opcion2[4]=80; //salta condicion
                            }
                        }while(opcion2[4]>32);
                        
                        do{
                            opcion2[5]=(int)(Math.random()*32);
                            if(opcion2[5]==opcion2[0] || opcion2[5]==opcion2[1]|| opcion2[5]==opcion2[2]|| opcion2[5]==opcion2[3]|| opcion2[5]==opcion2[4]){
                                opcion2[5]=80; //salta condicion
                            }
                        }while(opcion2[5]>32);
                        
                        do{
                            opcion2[6]=(int)(Math.random()*32);
                            if(opcion2[6]==opcion2[0] || opcion2[6]==opcion2[1]|| opcion2[6]==opcion2[2]|| opcion2[6]==opcion2[3]|| opcion2[6]==opcion2[4]|| opcion2[6]==opcion2[5]){
                                opcion2[6]=80; //salta condicion
                            }
                        }while(opcion2[6]>32);
                        
                        do{
                            opcion2[7]=(int)(Math.random()*32);
                            if(opcion2[7]==opcion2[0] || opcion2[7]==opcion2[1]|| opcion2[7]==opcion2[2]|| opcion2[7]==opcion2[3]|| opcion2[7]==opcion2[4]|| opcion2[7]==opcion2[5]|| opcion2[7]==opcion2[6]){
                                opcion2[7]=80; //salta condicion
                            }
                        }while(opcion2[7]>32);
                        
                        do{
                            opcion2[8]=(int)(Math.random()*32);
                            if(opcion2[8]==opcion2[0] || opcion2[8]==opcion2[1]|| opcion2[8]==opcion2[2]|| opcion2[8]==opcion2[3]|| opcion2[8]==opcion2[4]|| opcion2[8]==opcion2[5]|| opcion2[8]==opcion2[6]|| opcion2[8]==opcion2[7]){
                                opcion2[8]=80; //salta condicion
                            }
                        }while(opcion2[8]>32);
                        
                        do{
                            opcion2[9]=(int)(Math.random()*32);
                            if(opcion2[9]==opcion2[0] || opcion2[9]==opcion2[1]|| opcion2[9]==opcion2[2]|| opcion2[9]==opcion2[3]|| opcion2[9]==opcion2[4]|| opcion2[9]==opcion2[5]|| opcion2[9]==opcion2[6]|| opcion2[9]==opcion2[7]|| opcion2[9]==opcion2[8]){
                                opcion2[9]=80; //salta condicion
                            }
                        }while(opcion2[9]>32);
                        
                        do{
                            opcion2[10]=(int)(Math.random()*32);
                            if(opcion2[10]==opcion2[0] || opcion2[10]==opcion2[1]|| opcion2[10]==opcion2[2]|| opcion2[10]==opcion2[3]|| opcion2[10]==opcion2[4]|| opcion2[10]==opcion2[5]|| opcion2[10]==opcion2[6]|| opcion2[10]==opcion2[7]|| opcion2[10]==opcion2[8]|| opcion2[10]==opcion2[9]){
                                opcion2[10]=80; //salta condicion
                            }
                        }while(opcion2[10]>32);
                                                
                        do{
                            opcion2[11]=(int)(Math.random()*32);
                            if(opcion2[11]==opcion2[0] || opcion2[11]==opcion2[1]|| opcion2[11]==opcion2[2]|| opcion2[11]==opcion2[3]|| opcion2[11]==opcion2[4]|| opcion2[11]==opcion2[5]|| opcion2[11]==opcion2[6]|| opcion2[11]==opcion2[7]|| opcion2[11]==opcion2[8]|| opcion2[11]==opcion2[9]|| opcion2[11]==opcion2[10]){
                                opcion2[11]=80; //salta condicion
                            }
                        }while(opcion2[11]>32);
                        
                        do{
                            opcion2[12]=(int)(Math.random()*32);
                            if(opcion2[12]==opcion2[0] || opcion2[12]==opcion2[1]|| opcion2[12]==opcion2[2]|| opcion2[12]==opcion2[3]|| opcion2[12]==opcion2[4]|| opcion2[12]==opcion2[5]|| opcion2[12]==opcion2[6]|| opcion2[12]==opcion2[7]|| opcion2[12]==opcion2[8]|| opcion2[12]==opcion2[9]|| opcion2[12]==opcion2[10]|| opcion2[12]==opcion2[11]){
                                opcion2[12]=80; //salta condicion
                            }
                        }while(opcion2[12]>32);
                        
                        do{
                            opcion2[13]=(int)(Math.random()*32);
                            if(opcion2[13]==opcion2[0] || opcion2[13]==opcion2[1]|| opcion2[13]==opcion2[2]|| opcion2[13]==opcion2[3]|| opcion2[13]==opcion2[4]|| opcion2[13]==opcion2[5]|| opcion2[13]==opcion2[6]|| opcion2[13]==opcion2[7]|| opcion2[13]==opcion2[8]|| opcion2[13]==opcion2[9]|| opcion2[13]==opcion2[10]|| opcion2[13]==opcion2[11]|| opcion2[13]==opcion2[12]){
                                opcion2[13]=80; //salta condicion
                            }
                        }while(opcion2[13]>32);
                        
                        do{
                            opcion2[14]=(int)(Math.random()*32);
                            if(opcion2[14]==opcion2[0] || opcion2[14]==opcion2[1]|| opcion2[14]==opcion2[2]|| opcion2[14]==opcion2[3]|| opcion2[14]==opcion2[4]|| opcion2[14]==opcion2[5]|| opcion2[14]==opcion2[6]|| opcion2[14]==opcion2[7]|| opcion2[14]==opcion2[8]|| opcion2[14]==opcion2[9]|| opcion2[14]==opcion2[10]|| opcion2[14]==opcion2[11]|| opcion2[14]==opcion2[12]|| opcion2[14]==opcion2[13]){
                                opcion2[14]=80; //salta condicion
                            }
                        }while(opcion2[14]>32);
                        
                        do{
                            opcion2[15]=(int)(Math.random()*32);
                            if(opcion2[15]==opcion2[0] || opcion2[15]==opcion2[1]|| opcion2[15]==opcion2[2]|| opcion2[15]==opcion2[3]|| opcion2[15]==opcion2[4]|| opcion2[15]==opcion2[5]|| opcion2[15]==opcion2[6]|| opcion2[15]==opcion2[7]|| opcion2[15]==opcion2[8]|| opcion2[15]==opcion2[9]|| opcion2[15]==opcion2[10]|| opcion2[15]==opcion2[11]|| opcion2[15]==opcion2[12]|| opcion2[15]==opcion2[13]|| opcion2[15]==opcion2[14]){
                                opcion2[15]=80; //salta condicion
                            }
                        }while(opcion2[15]>32);
                        
                       
                        
                        
                        Equipo[] clasificados=new Equipo [16];
                        for(int i=0;i<16;i++){
                            clasificados[i]=equipos.getEquipos(opcion2[i]);
                        }
                        String s="";
                        Escribir.Escribir(s, false);
                        Equipo ganador;
                        ganador=SegundaFase.simular(clasificados);
                        resultado.setText("\nEl ganador de la segunda Fase es "+ganador.getNombre().trim());
                        botonRegistro.setEnabled(true);
                        
    }//GEN-LAST:event_botonAleatorioActionPerformed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        // TODO add your handling code here:
        VentanaRegistro window=new VentanaRegistro(padre,true);
        window.setVisible(true);
    }//GEN-LAST:event_botonRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton botonAleatorio;
    private javax.swing.JButton botonElegir;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonSimular;
    private javax.swing.JComboBox box1;
    private javax.swing.JComboBox box10;
    private javax.swing.JComboBox box11;
    private javax.swing.JComboBox box12;
    private javax.swing.JComboBox box13;
    private javax.swing.JComboBox box14;
    private javax.swing.JComboBox box15;
    private javax.swing.JComboBox box16;
    private javax.swing.JComboBox box2;
    private javax.swing.JComboBox box3;
    private javax.swing.JComboBox box4;
    private javax.swing.JComboBox box5;
    private javax.swing.JComboBox box6;
    private javax.swing.JComboBox box7;
    private javax.swing.JComboBox box8;
    private javax.swing.JComboBox box9;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
