
package vista;

import controlador.Escribir;
import controlador.ListaEquipos;
import controlador.SegundaFase;
import controlador.SimularFaseGrupos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import modelo.Equipo;
import modelo.FaseGrupos;
import modelo.Grupo;

/**
 *
 * @author Escar
 * 
 * VentanaMundial Muestra por pantalla el resultado del mundial Brazil 2014
 * permite la interaccion con el usuario solo para revisar el registro de lo ocurrido
 */
public class VentanaMundial extends javax.swing.JDialog {
    ListaEquipos equipos = new ListaEquipos();
    private VentanaP padre=(VentanaP) this.getParent();
    /**
     * Creates new form VentanaMundial
     */
    public VentanaMundial(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSimular = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Banner2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mundial");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Brazil 2014", 0, 24)); // NOI18N
        jLabel1.setText("Mundial");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        botonSimular.setBackground(new java.awt.Color(255, 255, 255));
        botonSimular.setText("Simular");
        botonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimularActionPerformed(evt);
            }
        });
        jPanel1.add(botonSimular, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 95, 45));

        resultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultado.setText("Resultado");
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 336, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/logo-copa.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        Banner2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/banner_02.jpg"))); // NOI18N
        jPanel1.add(Banner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/futbol2.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 420, 290));

        botonRegistro.setText("Registro");
        botonRegistro.setEnabled(false);
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 90, 40));

        jLabel2.setText("Espere unos segundos despues de simular");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, -1, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/rio.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 940, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimularActionPerformed
        // TODO add your handling code here:
        ListaEquipos equipos = new ListaEquipos();
        try {
            equipos.ListaEquipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMundial.class.getName()).log(Level.SEVERE, null, ex);
        }
        Grupo A= new Grupo("A", equipos.getEquipos(6),  equipos.getEquipos(13),  equipos.getEquipos(25),  equipos.getEquipos(7));
                Grupo B= new Grupo("B", equipos.getEquipos(15),  equipos.getEquipos(27), equipos.getEquipos(8),  equipos.getEquipos(3));
                Grupo C= new Grupo("C", equipos.getEquipos(9), equipos.getEquipos(19), equipos.getEquipos(11), equipos.getEquipos(24));
                Grupo D= new Grupo("D", equipos.getEquipos(31), equipos.getEquipos(12), equipos.getEquipos(21), equipos.getEquipos(23));
                Grupo E= new Grupo("E", equipos.getEquipos(30),  equipos.getEquipos(14),  equipos.getEquipos(17),  equipos.getEquipos(20));
                Grupo F= new Grupo("F", equipos.getEquipos(2), equipos.getEquipos(5), equipos.getEquipos(22), equipos.getEquipos(26));
                Grupo G= new Grupo("G", equipos.getEquipos(0), equipos.getEquipos(28), equipos.getEquipos(18), equipos.getEquipos(16));
                Grupo H= new Grupo("H", equipos.getEquipos(4), equipos.getEquipos(1), equipos.getEquipos(29), equipos.getEquipos(10));
       
                String s="";
                Escribir.Escribir(s, false);
                FaseGrupos fase = new FaseGrupos(A,B,C,D,E,F,G,H);
                Equipo[] winners=SimularFaseGrupos.simular(fase);
        
        
                for(int i=0;i<8;i++){
                    s=("Ganadores grupo:"+fase.getGrupos(i).getLetra()+" "+fase.getGrupos(i).getGanadores()[0].getNombre().trim()+"="+fase.getGrupos(i).getGanadores()[0].getPuntos()+", "+fase.getGrupos(i).getGanadores()[1].getNombre().trim()+"= "+fase.getGrupos(i).getGanadores()[1].getPuntos());
                    Escribir.Escribir(s, true);
                }
        
                s=("\n=================================\n");
                Escribir.Escribir(s, true);
                Equipo Ganadorsh =SegundaFase.simular(winners);
        
                resultado.setText("El Equipo ganador del Mundial es: " + Ganadorsh.getNombre().trim() );
                botonRegistro.setEnabled(true);
    }//GEN-LAST:event_botonSimularActionPerformed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        // TODO add your handling code here:
        VentanaRegistro window=new VentanaRegistro(padre,true);
            window.setVisible(true);
    }//GEN-LAST:event_botonRegistroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner2;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
