/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;
import controlador.*;
import javax.swing.DefaultListModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cancha;
import modelo.Pelota;
/**
 *
 * @author Escar
 */
public class VentanaPartidos extends javax.swing.JDialog {
    ListaEquipos equipos = new ListaEquipos();
    private VentanaP padre=(VentanaP) this.getParent();
    /**
     * Creates new form VentanaPartidos
     */
    public VentanaPartidos(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        equipos.ListaEquipos();
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < 32; i++) {
            modelo.addElement(equipos.getEquipos(i));
        }
        listaEquipo1.setModel(modelo);
        listaEquipo1.setEnabled(false);
        
        DefaultListModel modelo2 = new DefaultListModel();
        modelo2 = new DefaultListModel();
        for (int i = 0; i < 32; i++) {
            modelo2.addElement(equipos.getEquipos(i));
        }
        listaEquipo2.setModel(modelo2);
        listaEquipo2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEquipo2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEquipo1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonSimularPartido = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        botonSeleccionarEquipos = new javax.swing.JButton();
        botonEquiposAleatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Partido");

        listaEquipo2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEquipo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEquipo2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaEquipo2);

        listaEquipo1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEquipo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEquipo1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaEquipo1);

        jLabel2.setText("Equipo 2");

        jLabel3.setText("Equipo 1");

        botonSimularPartido.setText("Simular");
        botonSimularPartido.setEnabled(false);
        botonSimularPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimularPartidoActionPerformed(evt);
            }
        });

        resultado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                resultadoPropertyChange(evt);
            }
        });

        botonSeleccionarEquipos.setText("Seleccionar Equipos");
        botonSeleccionarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarEquiposActionPerformed(evt);
            }
        });

        botonEquiposAleatorios.setText("Equipos Aleatorios");
        botonEquiposAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEquiposAleatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonSeleccionarEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEquiposAleatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(botonSimularPartido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(botonSimularPartido)
                        .addGap(18, 18, 18)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonSeleccionarEquipos)
                        .addGap(18, 18, 18)
                        .addComponent(botonEquiposAleatorios)))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSimularPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimularPartidoActionPerformed
        // TODO add your handling code here:
        int index1 = listaEquipo1.getSelectedIndex();
        int index2 = listaEquipo2.getSelectedIndex();
        if(index1==index2){
            resultado.setText("Ingrese Equipos Distintos");
        }else{
        
        
        Pelota pelota=new Pelota();
        Cancha cancha=new Cancha();
        equipos.getEquipos(index1).setGoles(0);
        equipos.getEquipos(index2).setGoles(0);
        cancha.setEquipos(equipos.getEquipos(index1), 0);
        cancha.setEquipos(equipos.getEquipos(index2), 1);
        int[] n=SimularPartido.simularPartido(cancha, pelota, 0, 0);  // 0 0 arreglar formaciones
                       
        if(n[0]==0){
            resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
        }else if(n[0]==1){
            resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
        }else{
            int comp=0;//comprobante
            while(comp==0){
                int[] penal;
                penal=SimularPartido.penales(cancha);
                cancha.getEquipoX(0).setGoles(cancha.getEquipoX(0).getGoles()+penal[0]);
                cancha.getEquipoX(1).setGoles(cancha.getEquipoX(1).getGoles()+penal[1]);
                if (cancha.getEquipoX(0).getGoles()>cancha.getEquipoX(1).getGoles()){
                    n[0]=0;  
                    comp=1;
                }else if(cancha.getEquipoX(1).getGoles()>cancha.getEquipoX(0).getGoles()){
                    n[0]=1;
                    comp=1;
                }else{
                    comp=0;
                }
            }
            if(n[0]==0){
                resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
            }else if(n[0]==1){
                resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
            }
        }
 
        }
        listaEquipo1.setEnabled(false);
        listaEquipo2.setEnabled(false);
        botonSimularPartido.setEnabled(false);
    }//GEN-LAST:event_botonSimularPartidoActionPerformed

    private void resultadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_resultadoPropertyChange

        
    }//GEN-LAST:event_resultadoPropertyChange

    private void listaEquipo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEquipo1MouseClicked
        
        
    }//GEN-LAST:event_listaEquipo1MouseClicked

    private void listaEquipo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEquipo2MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_listaEquipo2MouseClicked

    private void botonSeleccionarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarEquiposActionPerformed
        // TODO add your handling code here:
        listaEquipo1.setEnabled(true);
        listaEquipo2.setEnabled(true);
        botonSimularPartido.setEnabled(true);
        
    }//GEN-LAST:event_botonSeleccionarEquiposActionPerformed

    private void botonEquiposAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEquiposAleatoriosActionPerformed
        // TODO add your handling code here:
        int index1=(int)(Math.random()*32);
        int index2 =(int)(Math.random()*32);
        while(index1==index2){
            index2 =(int)(Math.random()*32);
        }
        
        Pelota pelota=new Pelota();
        Cancha cancha=new Cancha();
        equipos.getEquipos(index1).setGoles(0);
        equipos.getEquipos(index2).setGoles(0);
        cancha.setEquipos(equipos.getEquipos(index1), 0);
        cancha.setEquipos(equipos.getEquipos(index2), 1);
        int[] n=SimularPartido.simularPartido(cancha, pelota, 0, 0);  // 0 0 arreglar formaciones
                       
        if(n[0]==0){
            resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
        }else if(n[0]==1){
            resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
        }else{
            int comp=0;//comprobante
            while(comp==0){
                int[] penal;
                penal=SimularPartido.penales(cancha);
                cancha.getEquipoX(0).setGoles(cancha.getEquipoX(0).getGoles()+penal[0]);
                cancha.getEquipoX(1).setGoles(cancha.getEquipoX(1).getGoles()+penal[1]);
                if (cancha.getEquipoX(0).getGoles()>cancha.getEquipoX(1).getGoles()){
                    n[0]=0;  
                    comp=1;
                }else if(cancha.getEquipoX(1).getGoles()>cancha.getEquipoX(0).getGoles()){
                    n[0]=1;
                    comp=1;
                }else{
                    comp=0;
                }
            }
            if(n[0]==0){
                resultado.setText("Equipo de "+equipos.getEquipos(index1).getNombre().trim()+" gana a "+equipos.getEquipos(index2).getNombre().trim()+" con "+equipos.getEquipos(index1).getGoles()+" goles a "+equipos.getEquipos(index2).getGoles());
            }else if(n[0]==1){
                resultado.setText("Equipo de "+equipos.getEquipos(index2).getNombre().trim()+" gana a "+equipos.getEquipos(index1).getNombre().trim()+" con "+equipos.getEquipos(index2).getGoles()+" goles a "+equipos.getEquipos(index1).getGoles());
            }
        }
 
        
    }//GEN-LAST:event_botonEquiposAleatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    VentanaPartidos dialog = new VentanaPartidos(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaPartidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEquiposAleatorios;
    private javax.swing.JButton botonSeleccionarEquipos;
    private javax.swing.JButton botonSimularPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaEquipo1;
    private javax.swing.JList listaEquipo2;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
